apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-eks-composition
spec:
  ignoreCrossplaneConstraints: false
  package: docker.io/vivekrsplunk/crossplane-eks-composition:7.0.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
